name: Auto Sync with Upstream

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/gallettilance/CS506-Fall2024.git
        git fetch upstream

    - name: Check for changes
      id: check_changes
      run: |
        git fetch upstream
        git diff --quiet upstream/main main || echo "changes=true" >> $GITHUB_ENV

    - name: Create Pull Request
      if: env.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: sync-upstream
        title: 'Sync with upstream repository'
        body: 'This PR syncs changes from the upstream repository.'
        commit-message: 'Sync with upstream repository'
        base: main
